export const PAGES = {
  MAIN: '/',
  WELCOME: '/welcome',
  LOGIN: '/login',
  REGISTER: '/register',
  RESET: '/reset-password',
  NEW_PASSWORD: '/new-password',
  TOS: '/tos',
  FAQ: '/faq',
  PRIVACY: '/privacy-policy',
  CATALOG: '/catalog',
  NEWS: '/news',
  USER: (id: string) => `/user/${id}`,
  COMMENTS: (id: string) => `/user/${id}/comments`,
  FRIENDS: (id: string) => `/user/${id}/friends`,
  SETTINGS: (id: string) => `/user/${id}/settings`,
  NEW_ANIME: '/new-anime',
} as const
